<?php

require_once dirname(__FILE__) . '/../../src/Field.php';

/**
 * Test class for Field.
 * Generated by PHPUnit on 2011-08-21 at 21:06:18.
 */
class FieldTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Field
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Field;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testSetSquare().
     */
    public function testSetSquare() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testPrintSolution().
     */
    public function testPrintSolution() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
