<?php

require_once dirname(__FILE__) . '/../../src/Minesweeper.php';

/**
 * Test class for Minesweeper.
 * Generated by PHPUnit on 2011-08-21 at 21:06:42.
 */
class MinesweeperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Minesweeper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Minesweeper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testSetData().
     */
    public function testSetData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testProcessData().
     */
    public function testProcessData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
