<?php

require_once dirname(__FILE__) . '/../../src/SquareSimple.php';

/**
 * Test class for SquareSimple.
 * Generated by PHPUnit on 2011-08-21 at 21:08:47.
 */
class SquareSimpleTest extends PHPUnit_Framework_TestCase {

    /**
     * @var SquareSimple
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SquareSimple;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testGetNumOfBombs().
     */
    public function testGetNumOfBombs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testIncrementNumOfBombs().
     */
    public function testIncrementNumOfBombs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
