<?php

require_once dirname(__FILE__) . '/../../src/SquareBomb.php';

/**
 * Test class for SquareBomb.
 * Generated by PHPUnit on 2011-08-21 at 21:08:25.
 */
class SquareBombTest extends PHPUnit_Framework_TestCase {

    /**
     * @var SquareBomb
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SquareBomb;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
